avoid using the sklarn `norm` function because it does not return the norm if sparse array are used. Use instead the numpy function.
NotImplementedError: return_norm=True is not implemented for sparse matrices with norm 'l1' or norm 'l2'